import Head from 'next/head';
import Image from 'next/image';

export default function Home() {
	return (
		<>
			<Head>
				<title>The Mighty Goku</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/goku-logo.png' />
			</Head>
			<header className='h-screen w-screen overflow-x-hidden flex items-center justify-center'>
				<div className='absolute flex items-center gap-2 top-4 left-4'>
					<img
						className='w-16 opacity-70'
						src='./goku-logo.png'
						alt='The Mighty Goku'
					/>
					<span className='font-bold text-xl text-gray-600'>
						The Mighty Goku
					</span>
				</div>
				<div>
					<p className='font-bold ml-2'>
						The <span className='text-orange-500'>Mighty</span>
					</p>
					<h1 className='text-9xl font-bold'>GOKU</h1>
				</div>
				<img
					className='max-h-[32rem] absolute top-[50%] transform translate-y-[-50%]'
					src='./goku-hero1.png'
					alt='The Mighty Goku'
				/>
				<img
					className='w-0 md:w-52 absolute top-[-2rem] right-[-3rem] opacity-70'
					src='./dragon-ball.png'
					alt='Dragon Ball'
				/>
			</header>

			<div className='mx-auto max-w-screen-md py-6 text-center'>
				<p className='text-2xl uppercase font-bold text-gray-900'>
					"May <span className='text-orange-500'>9</span> is goku day in{' '}
					<span className='text-orange-500'>japan</span>"
				</p>
			</div>

			<div className='md:flex py-4 px-8 items-center'>
				<div className='md:w-1/2 flex items-center justify-center'>
					<img className='w-[40%]' src='./goku4.png' alt='The Mighty Goku' />
				</div>
				<div className='md:w-1/2'>
					<h2 className='mb-3 font-bold text-3xl uppercase'>
						Son <span className='text-orange-500'>Goku</span>
					</h2>
					<p>
						<span className='font-bold'>Son Goku</span> is a Saiyan raised on
						Earth and the overall main protagonist of the Dragon Ball series.
						Originally sent to Earth as an infant, Kakarot would be adopted by
						Grandpa Gohan who named him Son Goku. A head injury at an early age
						alters Goku's memory, ridding him of his initial destructive nature
						and allowing him to grow up to become one of Earth's greatest
						defenders. He constantly strives and trains to be the greatest
						warrior possible, which has kept the Earth and the universe safe
						from destruction many times
					</p>
				</div>
			</div>

			<div className='md:flex gap-4 py-4 items-center justify-center'>
				<div className='md:w-1/2 w-full p-4'>
					<table className='w-full'>
						<tbody>
							<tr>
								<td>Name:</td>
								<td>Goku Kakarot</td>
							</tr>
							<tr>
								<td>Race:</td>
								<td>Saiyan</td>
							</tr>
							<tr>
								<td>Gender:</td>
								<td>Male</td>
							</tr>
							<tr>
								<td>Height:</td>
								<td>175cm</td>
							</tr>
							<tr>
								<td>Weight:</td>
								<td>62Kg</td>
							</tr>
							<tr>
								<td>Birth Date:</td>
								<td>Age 737 or Age 734 </td>
							</tr>
						</tbody>
					</table>
				</div>

				<img
					className='md:w-[16%] w-1/3 mx-auto'
					src='./goku-hero.png'
					alt='The Mighty Goku'
				/>
			</div>

			<div className='mx-auto max-w-screen-md py-6 '>
				<h2 className='mb-2 text-3xl text-center uppercase font-bold text-gray-900 '>
					Super Saiyan <span className='text-orange-500'>Forms</span>
				</h2>
				<p className='mb-6 text-center'>
					A lot has been done with the Super Saiyan concept since its initial
					appearance, and there is now a total of 21 different Super Saiyan
					forms in the Dragon Ball franchise.
				</p>
				<div className='grid grid-cols-2 md:grid-cols-3 gap-4'>
					<div className='relative flex flex-col items-center'>
						<div className='absolute z-[-10] bottom-8 w-40 h-40 bg-orange-200 rounded-full'></div>
						<img
							className='h-60 hover:opacity-80 transition duration-100s'
							src='./ssj-1.png'
							alt='Super Saiyan 1'
						/>
						<h3 className='font-bold'>
							Super Saiyan <span className='text-orange-500'>1</span>
						</h3>
					</div>
					<div className='relative flex flex-col items-center'>
						<div className='absolute z-[-10] bottom-8 w-40 h-40 bg-orange-200 rounded-full'></div>
						<img
							className='h-60 hover:opacity-80 transition duration-100s'
							src='./ssj-2.png'
							alt='Super Saiyan 2'
						/>
						<h3 className='font-bold'>
							Super Saiyan <span className='text-orange-500'>2</span>
						</h3>
					</div>
					<div className='relative flex flex-col items-center'>
						<div className='absolute z-[-10] bottom-8 w-40 h-40 bg-orange-200 rounded-full'></div>
						<img
							className='h-60 hover:opacity-80 transition duration-100s'
							src='./ssj-3.png'
							alt='Super Saiyan 3'
						/>
						<h3 className='font-bold'>
							Super Saiyan <span className='text-orange-500'>3</span>
						</h3>
					</div>
					<div className='relative flex flex-col items-center'>
						<div className='absolute z-[-10] bottom-8 w-40 h-40 bg-orange-200 rounded-full'></div>
						<img
							className='h-60 hover:opacity-80 transition duration-100s'
							src='./kaioken.webp'
							alt='Kaioken'
						/>
						<h3 className='font-bold'>
							<span className='text-orange-500'>Kaioken</span>
						</h3>
					</div>
					<div className='relative flex flex-col items-center'>
						<div className='absolute z-[-10] bottom-8 w-40 h-40 bg-orange-200 rounded-full'></div>
						<img
							className='h-60 hover:opacity-80 transition duration-100s'
							src='./ssj-red.png'
							alt='Super Saiyan Red'
						/>
						<h3 className='font-bold'>
							Super Saiyan <span className='text-orange-500'>Red</span>
						</h3>
					</div>
					<div className='relative flex flex-col items-center'>
						<div className='absolute z-[-10] bottom-8 w-40 h-40 bg-orange-200 rounded-full'></div>

						<img
							className='h-60 hover:opacity-80 transition duration-100s'
							src='./ssj-blue.png'
							alt='Super Saiyan Blue'
						/>
						<h3 className='font-bold'>
							Super Saiyan <span className='text-orange-500'>Blue</span>
						</h3>
					</div>
				</div>
			</div>

			<footer className='text-center py-4'>
				<p>
					© 2022 -{' '}
					<span className='text-orange-500 font-bold'>The Mighty Goku</span>.
					Built by <a href='https://www.mohaxmall.com'>Mohamed Mallahi</a>
				</p>
			</footer>
		</>
	);
}
