import Head from 'next/head';
import Image from 'next/image';

export default function Home() {
	return (
		<>
			<Head>
				<title>The Ambitious Naruto</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/Naruto-logo.png' />
			</Head>
			<header className='h-screen w-screen overflow-x-hidden flex items-center justify-center'>
				<div className='absolute flex items-center gap-2 top-4 left-4'>
					<img
						className='w-16 opacity-70'
						src='./naruto-logo.png'
						alt='The Ambitious Naruto'
					/>
					<span className='font-bold text-xl text-gray-600'>
						The Ambitious Naruto
					</span>
				</div>
				<div>
					<p className='font-bold ml-2'>
						The <span className='text-yellow-500'>Ambitious</span>
					</p>
					<h1 className='text-9xl font-bold'>NARUTO</h1>
				</div>
				<img
					className='max-h-[32rem] absolute top-[50%] transform translate-y-[-50%]'
					src='./naruto-hero.png'
					alt='The Ambitious Naruto'
				/>
				<img
					className='w-0 md:w-56 absolute top-0 right-[-3rem] opacity-70'
					src='./kyuubi.jpg'
					alt='Kyuubi'
				/>
			</header>

			<div className='mx-auto max-w-screen-md py-6 text-center'>
				<p className='text-2xl uppercase font-bold text-gray-900 dark:text-white'>
					"October <span className='text-yellow-500'>9</span> is Naruto day in{' '}
					<span className='text-yellow-500'>japan</span>"
				</p>
			</div>

			<div className='md:flex py-4 px-8 items-center'>
				<div className='md:w-1/2 flex items-center justify-center'>
					<img
						className='w-[45%]'
						src='./naruto.png'
						alt='The Ambitious Naruto'
					/>
				</div>
				<div className='md:w-1/2'>
					<h2 className='mb-3 font-bold text-3xl uppercase'>
						Uzumaki <span className='text-yellow-500'>Naruto</span>
					</h2>
					<p>
						<span className='font-bold'>Uzumaki Naruto</span> is a shinobi of
						Konohagakure's Uzumaki clan. He became the jinchūriki of the
						Nine-Tails on the day of his birth — a fate that caused him to be
						shunned by most of Konoha throughout his childhood. After joining
						Team Kakashi, Naruto worked hard to gain the village's
						acknowledgement all the while chasing his dream to become Hokage.
					</p>
				</div>
			</div>

			<div className='md:flex gap-4 py-4 items-center justify-center'>
				<div className='md:w-1/2 w-full p-4'>
					<table className='w-full'>
						<tbody>
							<tr>
								<td>Name:</td>
								<td>Luffy Kakarot</td>
							</tr>
							<tr>
								<td>Race:</td>
								<td>Saiyan</td>
							</tr>
							<tr>
								<td>Gender:</td>
								<td>Male</td>
							</tr>
							<tr>
								<td>Height:</td>
								<td>175cm</td>
							</tr>
							<tr>
								<td>Weight:</td>
								<td>62Kg</td>
							</tr>
							<tr>
								<td>Birth Date:</td>
								<td>Age 737 or Age 734 </td>
							</tr>
						</tbody>
					</table>
				</div>

				<img
					className='md:w-[16%] w-1/3 mx-auto'
					src='./Luffy-hero.png'
					alt='The Ambitious Luffy'
				/>
			</div>

			<div className='mx-auto max-w-screen-md py-6 '>
				<h2 className='mb-2 text-3xl text-center uppercase font-bold text-gray-900 dark:text-white'>
					Luffy Gears <span className='text-yellow-500'>Forms</span>
				</h2>
				<p className='mb-6 text-center'>
					A lot has been done with the Super Saiyan concept since its initial
					appearance, and there is now a total of 21 different Super Saiyan
					forms in the Dragon Ball franchise.
				</p>
				<div className='grid grid-cols-2 md:grid-cols-3 gap-4'>
					<div className='flex flex-col items-center '>
						<img className='h-60' src='./gear-2.webp' alt='Super Saiyan 1' />
						<h3 className='font-bold'>
							Gear <span className='text-yellow-500'>2</span>
						</h3>
					</div>
					<div className='flex flex-col items-center '>
						<img className='h-60' src='./gear-3.webp' alt='Super Saiyan 2' />
						<h3 className='font-bold'>
							Gear <span className='text-yellow-500'>3</span>
						</h3>
					</div>
					<div className='flex flex-col items-center '>
						<img
							className='h-60'
							src='./gear-4b.webp'
							alt='Gear 4th: Bound Man'
						/>
						<h3 className='font-bold'>
							Gear
							<span className='text-yellow-500'> 4th: Bound Man</span>
						</h3>
					</div>
					<div className='flex flex-col items-center '>
						<img className='h-60' src='./gear-4t.webp' alt='Kaioken' />
						<h3 className='font-bold'>
							Gear
							<span className='text-yellow-500'>4th: Tankman Full Version</span>
						</h3>
					</div>
					<div className='flex flex-col items-center '>
						<img
							className='h-60'
							src='./gear-4s.webp'
							alt='Gear 4th: Snakeman'
						/>
						<h3 className='font-bold'>
							Gear <span className='text-yellow-500'>4th: Snakeman</span>
						</h3>
					</div>
					<div className='flex flex-col items-center '>
						<img className='h-60' src='./gear-5.png' alt='Gear 4th: Snakeman' />
						<h3 className='font-bold'>
							Devil Fruit <span className='text-yellow-500'>Awakening</span>
						</h3>
					</div>
				</div>
			</div>

			<footer className='text-center py-4'>
				<p>
					© 2022 -{' '}
					<span className='text-yellow-500 font-bold'>
						The Ambitious NAruti
					</span>
					. All rights reserved.
				</p>
			</footer>
		</>
	);
}
